### PR TITLE
WIP - Ensure audit logs compress deltas and results to save space

### PR DESCRIPTION
**Pull request by mmoayyed**
# DO NOT MERGE

### CODE REVIEW

**Comment by 1azyman** [comment]
Hi Misagh, thank you very much for PR. One thing that this PR is missing are upgrade scripts. Your implementation of upgrade scripts would work only for empty tables I guess. I think, for non empty tables you will have to:
1/ alter table, add new columns with proper type
2/ copy data from old columns while doing data type transformation and compression
3/ drop old columns and rename new ones

Can you have a look at it please?

**Comment by mmoayyed** [comment]
Sure thing. Updates incoming.

**Comment by mmoayyed** [comment]
Reviewing this. Questions:

1. How do we test the upgrade script for all supported database types?
2. Are there specific practices in midPoint to convert one CLOB data type into a BLOB?

**Comment by 1azyman** [comment]
1/ unfortunately, just manual way. I've created docker compose project with DBs to simplyfy testing but that's it... https://github.com/1azyman/docker-databases
2/ nope, wasn't needed before
if necessary we can leave upgrade scripts for later, jira task would have to be created with high priority.

**Comment by 1azyman** [comment]
Hi Misagh,
tests are still failing. I checked code and found 2 issues:
1/ decompression is not handled correctly in RObjectDeltaOperation.fromRepo()
2/ RUtil.computeChecksum() doesn't work correctly. Proper way would be chaining ByteArrayInputStreams with SequenceInputStream as we changed String to byte[]

I'll create JIRA for upgrade scripts, so we can move with our testing and prepare them in parallel.

**Comment by 1azyman** [comment]
So today's your lucky day. I wanted to merge other DB changes so I merged this as well and fixed that two small issues. Only thing that remains are update scripts. Thanks a lot for PR.

**Pull request merged**
