### PR TITLE
Let travis run the build with 10 threads

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by PetrGasparik** [comment]
Hi Misagh, the travis is broken, please fix it.

If I understand correctly, the build is now run in parallel. If that's true, there can be some hitches - the build rely on sequential run.

**Comment by martin-lizner** [comment]
Thanks for the PR! However, I would advice to close this PR without merging from following reasons:
- Integration tests cannot be run in parallel without design changes as @PetrGasparik mentioned
- Build/Install part can teoretically be parallelized, but it takes like 5% of the overall job time. I tried using 10 threads on local with about 30% boost in speed. Which makes it like 2% from total job time.
- When separating "mvn clean install skipTests" from "mvn test" ICF behaves strangly and will not find Dummy connector. And for the reason mentioned above I think its not worth spending effort on it.

**Comment by mmoayyed** [comment]
Sure. no problem

**Comment by semancik** [comment]
This is indeed a thin ice. Almost all integration tests are starting embedded H2 database. And currently they use the same (hardcoded) port and filesystem path. So we will need to make these separate for each test. It should be possible as all the tests use the same init code. But currently we have more important priorities. I'm OK with closing this pull request without merging. I've created jira issue so we won't forget about this:
https://jira.evolveum.com/browse/MID-3377
However, I'm not able to plan to any specific release now. Unless somebody volunteers to do the work, of course.

**Pull request closed without merging**
