### PR TITLE
Fixes saving case outcome and evidence (ports changes to 3.9 support branch)

### PR DESCRIPTION
**Pull request by bpowers1215**
Bug Fix: Correct closed case outcome value
Bug Fix: Correctly save evidence to case work item outcome

This PR contains the bug fixes originally introduced as part of #85
These items were split into another PR since time has not allowed us to complete the UI change feedback in the original ticket, and to prevent holding up bug fixes for future versions.

### CODE REVIEW

**Comment by alexandrezia** [comment]
Awesome, great!
Thanks for this.

**Comment by mederly** [comment]
@bpowers1215 Brandon, thank you! I have merged it.

But, may I ask, what exactly was problem with the original code `.item(CaseType.F_WORK_ITEM, workItemId, WorkItemType.F_OUTPUT).replace(output)` ? Your current code is functionally equivalent (at least I think so) but only until `AbstractWorkItemOutputType` is extended.

**Comment by PetrGasparik** [comment]
> @bpowers1215 Brandon, thank you! I have merged it.
> 
> But, may I ask, what exactly was problem with the original code `.item(CaseType.F_WORK_ITEM, workItemId, WorkItemType.F_OUTPUT).replace(output)` ? Your current code is functionally equivalent (at least I think so) but only until `AbstractWorkItemOutputType` is extended.

The same here... @bpowers1215 , @alexandrezia  - the change to .replace(output) looks like step down from generality.

**Comment by bpowers1215** [comment]
Yes, you are correct, this code is fundamentally the same.  However, there seem to be a bug with the former logic.  Though the `.replace(output)` worked at surface level, the attributes of `output` were not being saved correctly, causing information loss.  This may have been an issue of deep vs shallow copying, perhaps.  As a patch, I opted for the more granular method of saving the information to ensure the output info was set correctly.  It is probably best that the `.replace(output)` functionality be re-examined to determine why the outcome was not as expected.

**Pull request merged**
