### PR TITLE
MID-7090: GUI Info Dashboard System status panel - DB connections stats

### PR DESCRIPTION
**Pull request by martin-lizner**
Tested on Postgres and H2. Please cherry pick to master.

### CODE REVIEW

**Comment by martin-lizner** [comment]
I fix the failing test first

**Comment by martin-lizner** [comment]
merge status pls?

**Comment by martin-lizner** [comment]
gentle reminder...

**Comment by mederly** [comment]
Hello @martin-lizner ! 

Thank you for the contribution. It's my fault that I have forgotten to review it sooner.
Everything is fine but ... let me ask: why have you choose to place the `getDBPoolStats` method to `TaskManager` and not to `RepositoryService` where it perhaps belong?

**Comment by martin-lizner** [comment]
Hi, RepositoryService was my first attempt. Unfortunatelly I havent found easy way how to call it from SystemInfoPanel. Also we are having cache implementation which does not have hikari stats. While TaskManager bean is just there. I know its a little tradeoff :-(

**Comment by mederly** [comment]
I have merged your code, thanks. As for the exact positioning of the method, we'll improve that later.

**Pull request merged**
