### PR TITLE
Fixes saving case outcome and evidence

### PR DESCRIPTION
**Pull request by bpowers1215**
Bug Fix: Correct closed case outcome value
Bug Fix: Correctly save evidence to case work item outcome

This PR contains the bug fixes originally introduced as part of https://github.com/Evolveum/midpoint/pull/85
These items were split into another PR since time has not allowed us to complete the UI change feedback in the original ticket, and to prevent holding up bug fixes for future versions.

### CODE REVIEW

**Comment by martin-lizner** [comment]
Thanks for this PR. Is it portable to 3.9-support? Does it cover bug, when closed case is still represented as Executing (or In progress) in projections?

**Comment by bpowers1215** [comment]
@martin-lizner - Yes, this covers the bug fix for the projection shadow pending delta status based on case status (with this change, the shadow refresh task should successfully update the pending delta status).  

This can be ported to support-3.9, I opened a PR here: https://github.com/Evolveum/midpoint/pull/94

**Comment by alexandrezia** [comment]
Awesome, great!
Thanks for this.

**Comment by martin-lizner** [comment]
@bpowers1215 Thanks a lot man!

**Comment by martin-lizner** [comment]
@bpowers1215 We installed new 3.9-support build and after closing the case, the shadow still contains pendingOperation exucuting/in_progress. How do we refresh it, what exactly is "the shadow refresh task" ?

**Comment by bpowers1215** [comment]
@martin-lizner There is a task handler available for shadowRefresh.  See the following example in MidPoint repository: https://github.com/Evolveum/midpoint/blob/master/model/model-intest/src/test/resources/manual/task-shadow-refresh.xml and this documentation: https://wiki.evolveum.com/display/midPoint/Manual+Resource+Configuration#ManualResourceConfiguration-RefreshTask

**Pull request closed without merging**
